# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

# Copy the requirements.txt first
COPY requirements.txt /app/

# Increase pip timeout
ENV PIP_DEFAULT_TIMEOUT=3000000

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the app
COPY . /app

# Expose port and run the app
EXPOSE 10000
CMD ["python", "app.py"]
